var MILWAUKEE_DRILL_PRODUCT = new Map();
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_NAME", "Milwaukee Drill");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_CATEGORY", "Tools");


var CANON_R50_CAMERA_PRODUCT = new Map();
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_NAME", "Canon R50 Camera");
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", false);
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Premium");
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall Camera, Works Great");
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_IMAGE", "Technology");


var ALL_PROUDCT_MAPS = new Map();
ALL_PROUDCT_MAPS.set("PRODUCT_1", MILWAUKEE_DRILL_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_2", CANON_R50_CAMERA_PRODUCT);

