var MILWAUKEE_DRILL_PRODUCT = new Map();
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_NAME", "Milwaukee M18 Compact Drill 1/2\" ");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/milwaukee_drill_m18.webp");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$150");

var MILWAUKEE_JIGSAW_PRODUCT = new Map();
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_NAME", "M18 FUEL 18V Lithium-Ion Brushless Cordless Jig Saw");
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall jigsaw, Works Great");
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/milwaukee_jigsaw_m18.webp");
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
MILWAUKEE_JIGSAW_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$229");

var MILWAUKEE_CIRCULAR_SAW_PRODUCT = new Map();
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_NAME", "M18 18V Lithium-Ion Cordless 6-1/2 in. Circular Saw");
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall circular saw, Works Great");
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/milwaukee_saw_m18.webp");
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
MILWAUKEE_CIRCULAR_SAW_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$149");

var MILWAUKEE_STAPLER_PRODUCT = new Map();
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_NAME", "M12 12-Volt Lithium-Ion Cordless 3/8 in. Crown Stapler");
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall stapler, Works Great");
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/milwaukee_stapler_m12.webp");
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
MILWAUKEE_STAPLER_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$139");

var MILWAUKEE_SANDER_PRODUCT = new Map();
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_NAME", "M18 18V Lithium-Ion Cordless 5 in. Random Orbit Sander");
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall orbital sander, Works Great");
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/milwaukee_sander_m18.webp");
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
MILWAUKEE_SANDER_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$149");

var PRECISION_MEASURE_BLOCKS_PRODUCT = new Map();
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_NAME", "Setup Blocks Height Gauge Set, 15pcs Precision Aluminum Setup Bars");
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for table saws and band saws to precisely measure.");
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/precision_measure_blocks.webp");
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
PRECISION_MEASURE_BLOCKS_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$39");

var PRECISION_MACHINIST_SQUARE_PRODUCT = new Map();
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_NAME", "Machinist Square, 4\" x 3\", 90 Degree Right Angle Steel");
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for wood working projects that requre precision.");
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/machinist_square.webp");
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
PRECISION_MACHINIST_SQUARE_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$31");

var JAPANESE_WOODWORKING_MALLET_PRODUCT = new Map();
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_NAME", "Japanese Woodworking Hammer 10.5 oz (300g) Flat & Rounded Faces");
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for wood working projects.");
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/japanese_mallet_10.webp");
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
JAPANESE_WOODWORKING_MALLET_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$31");

var JAPANESE_WOODWORKING_FINE_SAW_PRODUCT = new Map();
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_NAME", "Z-Saw Dozuki Fine 150 Japanese Pull-Saw");
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for wood working projects.");
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/japanese_woodworking_saw.webp");
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
JAPANESE_WOODWORKING_FINE_SAW_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$30");

var JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT = new Map();
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_NAME", "SUIZAN Ryoba Double Edge Saw 9.5\"");
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for wood working projects.");
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/japanese_woodworking_ryoba_saw.webp");
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$42");

var WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT = new Map();
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_NAME", "Wheel Marking Gauge");
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for wood working projects.");
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/circular_marking_gauge.webp");
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$25");

var WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT = new Map();
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_NAME", "JORGENSEN NO.60-1/2 6-1/4\" Wood Planer, Hand Planer");
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for wood working projects.");
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/hand_planer_jorgensen.webp");
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$43");

var WOODWORKING_CLAMP_PRODUCT = new Map();
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_NAME", "Variety of Clamps for Wood Working");
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for wood working projects.");
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/woodworking_clamp.webp");
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
WOODWORKING_CLAMP_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$12");

var BASIC_HARD_HAT_PRODUCT = new Map();
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_NAME", "Basic Hard Hat");
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for basic safety. They are also required when using a landfill");
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/basic_hard_hat.webp");
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_DEPOSIT", "$1");
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
BASIC_HARD_HAT_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$5");

var TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT = new Map();
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_NAME", "Red Mesh Safety Warning Flags for Truck");
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for trucks carrying long items.");
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/truck_overhang_flag.webp");
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_DEPOSIT", "$5");
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$20");

var BASIC_KNEE_PADS_PRODUCT = new Map();
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_NAME", "Kobalt Flooring Knee Pads");
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for knee relief when working long periods on the ground.");
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/basic_knee_pads.webp");
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_DEPOSIT", "$5");
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
BASIC_KNEE_PADS_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$20");

var HAND_PLANER_5_JORGENSEN_PRODUCT = new Map();
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_NAME", "JORGENSEN No.5 Wood Planer, Professional Hand Planer");
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for wood working projects.");
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/hand_planer_5_jorgensen.webp");
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
HAND_PLANER_5_JORGENSEN_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$103");

var THREE_M_EAR_PROTECTION_PRODUCT = new Map();
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_NAME", "3M Pro-Grade Earmuff");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for loud projects.");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/3m_sound_ear_protection.webp");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_DEPOSIT", "$5");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$27");

var THREE_M_EAR_PROTECTION_PRODUCT = new Map();
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_NAME", "3M Pro-Grade Earmuff");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for loud projects.");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/3m_sound_ear_protection.webp");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_DEPOSIT", "$5");
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
THREE_M_EAR_PROTECTION_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$27");

var GENERIC_CAULK_GUN_PRODUCT = new Map();
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_NAME", "Generic Caulk Gun");
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_DESCRIPTION", "Great to use canisters like liquid nail or caulks.");
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/generic_caulk_gun.webp");
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_DEPOSIT", "$1");
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
GENERIC_CAULK_GUN_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$5");

var BOW_FEATHER_BOARD_PRODUCT = new Map();
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_NAME", "BOW Products EVA Featherboard");
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_DESCRIPTION", "Great for table saws, router tables, and band saws.");
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/table_saw_feather_board.webp");
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
BOW_FEATHER_BOARD_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$38");

var MILWAUKEE_DRILL_BITS_PRODUCT = new Map();
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_NAME", "SHOCKWAVE Impact Duty Alloy Steel Screw Driver Bit Set");
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_DESCRIPTION", "Great drills.");
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_IMAGE", "./images/tool_photos/milwaukee_drill_bits.webp");
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);
MILWAUKEE_DRILL_BITS_PRODUCT.set("PRODUCT_RETAIL_PRICE", "$30");


var ALL_PROUDCT_MAPS = new Map();
ALL_PROUDCT_MAPS.set("PRODUCT_1", MILWAUKEE_DRILL_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_2", MILWAUKEE_JIGSAW_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_3", MILWAUKEE_CIRCULAR_SAW_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_4", MILWAUKEE_STAPLER_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_5", MILWAUKEE_SANDER_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_6", PRECISION_MEASURE_BLOCKS_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_7", PRECISION_MACHINIST_SQUARE_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_8", JAPANESE_WOODWORKING_MALLET_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_9", JAPANESE_WOODWORKING_FINE_SAW_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_10", JAPANESE_WOODWORKING_RYOBA_DOUBLE_EDGE_SAW_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_11", WOODWORKING_WHEEL_MARKING_GAUGE_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_12", WOODWORKING_WOOD_HAND_PLANER_60_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_13", WOODWORKING_CLAMP_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_14", BASIC_HARD_HAT_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_15", TRUCK_SAFETY_WARNING_FLAGS_TRUCK_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_16", BASIC_KNEE_PADS_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_17", THREE_M_EAR_PROTECTION_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_18", GENERIC_CAULK_GUN_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_19", BOW_FEATHER_BOARD_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_20", MILWAUKEE_DRILL_BITS_PRODUCT);



var DISPLAYED_PRODUCTS = ALL_PROUDCT_MAPS;