var MILWAUKEE_DRILL_PRODUCT = new Map();
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_NAME", "Milwaukee Drill");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", true);



var CANON_R50_CAMERA_PRODUCT = new Map();
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_NAME", "Canon R50 Camera");
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_CHECKOUT_STATUS", false);
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_MEMBERSHIP_STATUS", "Premium");
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_DESCRIPTION", "Great Overall Camera, Works Great");
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_CATEGORY", "Technology");
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_DEPOSIT", "$30");
CANON_R50_CAMERA_PRODUCT.set("PRODUCT_WITHOUT_MEMBERSHIP", false);

var MILWAUKEE_DRILL_PRODUCT1 = new Map();
MILWAUKEE_DRILL_PRODUCT1.set("PRODUCT_NAME", "Milwaukee Drill 1");
MILWAUKEE_DRILL_PRODUCT1.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT1.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT1.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT1.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT1.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT1.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT1.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT2 = new Map();
MILWAUKEE_DRILL_PRODUCT2.set("PRODUCT_NAME", "Milwaukee Drill 2");
MILWAUKEE_DRILL_PRODUCT2.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT2.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT2.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT2.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT2.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT2.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT2.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT3 = new Map();
MILWAUKEE_DRILL_PRODUCT3.set("PRODUCT_NAME", "Milwaukee Drill3");
MILWAUKEE_DRILL_PRODUCT3.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT3.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT3.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT3.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT3.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT3.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT3.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT4 = new Map();
MILWAUKEE_DRILL_PRODUCT4.set("PRODUCT_NAME", "Milwaukee Drill4");
MILWAUKEE_DRILL_PRODUCT4.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT4.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT4.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT4.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT4.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT4.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT4.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT5 = new Map();
MILWAUKEE_DRILL_PRODUCT5.set("PRODUCT_NAME", "Milwaukee Drill5");
MILWAUKEE_DRILL_PRODUCT5.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT5.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT5.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT5.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT5.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT5.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT5.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT6 = new Map();
MILWAUKEE_DRILL_PRODUCT6.set("PRODUCT_NAME", "Milwaukee Drill6");
MILWAUKEE_DRILL_PRODUCT6.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT6.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT6.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT6.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT6.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT6.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT6.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT7 = new Map();
MILWAUKEE_DRILL_PRODUCT7.set("PRODUCT_NAME", "Milwaukee Drill7");
MILWAUKEE_DRILL_PRODUCT7.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT7.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT7.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT7.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT7.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT7.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT7.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT8 = new Map();
MILWAUKEE_DRILL_PRODUCT8.set("PRODUCT_NAME", "Milwaukee Drill8");
MILWAUKEE_DRILL_PRODUCT8.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT8.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT8.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT8.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT8.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT8.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT8.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT9 = new Map();
MILWAUKEE_DRILL_PRODUCT9.set("PRODUCT_NAME", "Milwaukee Drill");
MILWAUKEE_DRILL_PRODUCT9.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT9.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT9.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT9.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT9.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT9.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT9.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT10 = new Map();
MILWAUKEE_DRILL_PRODUCT10.set("PRODUCT_NAME", "Milwaukee Drill9");
MILWAUKEE_DRILL_PRODUCT10.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT10.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT10.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT10.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT10.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT10.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT10.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT11 = new Map();
MILWAUKEE_DRILL_PRODUCT11.set("PRODUCT_NAME", "Milwaukee Drill10");
MILWAUKEE_DRILL_PRODUCT11.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT11.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT11.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT11.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT11.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT11.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT11.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT12 = new Map();
MILWAUKEE_DRILL_PRODUCT12.set("PRODUCT_NAME", "Milwaukee Drill11");
MILWAUKEE_DRILL_PRODUCT12.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT12.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT12.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT12.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT12.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT12.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT12.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT13 = new Map();
MILWAUKEE_DRILL_PRODUCT13.set("PRODUCT_NAME", "Milwaukee Drill12");
MILWAUKEE_DRILL_PRODUCT13.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT13.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT13.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT13.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT13.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT13.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT13.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT14 = new Map();
MILWAUKEE_DRILL_PRODUCT14.set("PRODUCT_NAME", "Milwaukee Drill13");
MILWAUKEE_DRILL_PRODUCT14.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT14.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT14.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT14.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT14.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT14.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT14.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT15 = new Map();
MILWAUKEE_DRILL_PRODUCT15.set("PRODUCT_NAME", "Milwaukee Drill14");
MILWAUKEE_DRILL_PRODUCT15.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT15.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT15.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT15.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT15.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT15.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT15.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT16 = new Map();
MILWAUKEE_DRILL_PRODUCT16.set("PRODUCT_NAME", "Milwaukee Drill15");
MILWAUKEE_DRILL_PRODUCT16.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT16.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT16.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT16.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT16.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT16.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT16.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT17 = new Map();
MILWAUKEE_DRILL_PRODUCT17.set("PRODUCT_NAME", "Milwaukee Drill16");
MILWAUKEE_DRILL_PRODUCT17.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT17.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT17.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT17.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT17.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT17.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT17.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT18 = new Map();
MILWAUKEE_DRILL_PRODUCT18.set("PRODUCT_NAME", "Milwaukee Drill17");
MILWAUKEE_DRILL_PRODUCT18.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT18.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT18.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT18.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT18.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT18.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT18.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT19 = new Map();
MILWAUKEE_DRILL_PRODUCT19.set("PRODUCT_NAME", "Milwaukee Drill18");
MILWAUKEE_DRILL_PRODUCT19.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT19.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT19.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT19.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT19.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT19.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT19.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT20 = new Map();
MILWAUKEE_DRILL_PRODUCT20.set("PRODUCT_NAME", "Milwaukee Drill19");
MILWAUKEE_DRILL_PRODUCT20.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT20.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT20.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT20.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT20.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT20.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT20.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT21 = new Map();
MILWAUKEE_DRILL_PRODUCT21.set("PRODUCT_NAME", "Milwaukee Drill20");
MILWAUKEE_DRILL_PRODUCT21.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT21.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT21.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT21.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT21.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT21.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT21.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT22 = new Map();
MILWAUKEE_DRILL_PRODUCT22.set("PRODUCT_NAME", "Milwaukee Drill21");
MILWAUKEE_DRILL_PRODUCT22.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT22.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT22.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT22.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT22.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT22.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT22.set("PRODUCT_WITHOUT_MEMBERSHIP", true);

var MILWAUKEE_DRILL_PRODUCT23 = new Map();
MILWAUKEE_DRILL_PRODUCT23.set("PRODUCT_NAME", "Milwaukee Drill22");
MILWAUKEE_DRILL_PRODUCT23.set("PRODUCT_CHECKOUT_STATUS", true);
MILWAUKEE_DRILL_PRODUCT23.set("PRODUCT_MEMBERSHIP_STATUS", "Standard");
MILWAUKEE_DRILL_PRODUCT23.set("PRODUCT_DESCRIPTION", "Great Overall Drill, Works Great");
MILWAUKEE_DRILL_PRODUCT23.set("PRODUCT_IMAGE", "");
MILWAUKEE_DRILL_PRODUCT23.set("PRODUCT_CATEGORY", "Tools");
MILWAUKEE_DRILL_PRODUCT23.set("PRODUCT_DEPOSIT", "$10");
MILWAUKEE_DRILL_PRODUCT23.set("PRODUCT_WITHOUT_MEMBERSHIP", true);


var ALL_PROUDCT_MAPS = new Map();
ALL_PROUDCT_MAPS.set("PRODUCT_1", MILWAUKEE_DRILL_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_2", CANON_R50_CAMERA_PRODUCT);
ALL_PROUDCT_MAPS.set("PRODUCT_3", MILWAUKEE_DRILL_PRODUCT1);
ALL_PROUDCT_MAPS.set("PRODUCT_4", MILWAUKEE_DRILL_PRODUCT2);
ALL_PROUDCT_MAPS.set("PRODUCT_5", MILWAUKEE_DRILL_PRODUCT3);
ALL_PROUDCT_MAPS.set("PRODUCT_6", MILWAUKEE_DRILL_PRODUCT4);
ALL_PROUDCT_MAPS.set("PRODUCT_7", MILWAUKEE_DRILL_PRODUCT5);
ALL_PROUDCT_MAPS.set("PRODUCT_8", MILWAUKEE_DRILL_PRODUCT6);
ALL_PROUDCT_MAPS.set("PRODUCT_9", MILWAUKEE_DRILL_PRODUCT7);
ALL_PROUDCT_MAPS.set("PRODUCT_10", MILWAUKEE_DRILL_PRODUCT8);
ALL_PROUDCT_MAPS.set("PRODUCT_11", MILWAUKEE_DRILL_PRODUCT9);
ALL_PROUDCT_MAPS.set("PRODUCT_12", MILWAUKEE_DRILL_PRODUCT10);
ALL_PROUDCT_MAPS.set("PRODUCT_13", MILWAUKEE_DRILL_PRODUCT11);
ALL_PROUDCT_MAPS.set("PRODUCT_14", MILWAUKEE_DRILL_PRODUCT12);
ALL_PROUDCT_MAPS.set("PRODUCT_15", MILWAUKEE_DRILL_PRODUCT13);
ALL_PROUDCT_MAPS.set("PRODUCT_16", MILWAUKEE_DRILL_PRODUCT14);
ALL_PROUDCT_MAPS.set("PRODUCT_17", MILWAUKEE_DRILL_PRODUCT15);
ALL_PROUDCT_MAPS.set("PRODUCT_18", MILWAUKEE_DRILL_PRODUCT16);
ALL_PROUDCT_MAPS.set("PRODUCT_19", MILWAUKEE_DRILL_PRODUCT17);
ALL_PROUDCT_MAPS.set("PRODUCT_20", MILWAUKEE_DRILL_PRODUCT18);
ALL_PROUDCT_MAPS.set("PRODUCT_21", MILWAUKEE_DRILL_PRODUCT19);
ALL_PROUDCT_MAPS.set("PRODUCT_22", MILWAUKEE_DRILL_PRODUCT20);
ALL_PROUDCT_MAPS.set("PRODUCT_23", MILWAUKEE_DRILL_PRODUCT21);
ALL_PROUDCT_MAPS.set("PRODUCT_24", MILWAUKEE_DRILL_PRODUCT22);
ALL_PROUDCT_MAPS.set("PRODUCT_25", MILWAUKEE_DRILL_PRODUCT23);


var DISPLAYED_PRODUCTS = ALL_PROUDCT_MAPS;